"""simple

Revision ID: 1a05e04104cc
Revises: 138e0bf0c721
Create Date: 2022-11-17 07:38:23.067209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a05e04104cc'
down_revision = '138e0bf0c721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'server_address')
    op.drop_column('session', 'is_bot')
    op.drop_column('session', 'port')
    op.drop_column('session', 'api_id')
    op.drop_column('session', 'test_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('test_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('is_bot', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('server_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
