"""user balance

Revision ID: 602f2af6ebb5
Revises: 5204696cd6e5
Create Date: 2023-01-02 17:07:51.436156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602f2af6ebb5'
down_revision = '5204696cd6e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.BigInteger(), nullable=True))
    op.drop_column('user', 'proxy_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('proxy_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
