"""filename

Revision ID: abd8acc67696
Revises: cccca093ce60
Create Date: 2022-12-30 09:29:44.849498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd8acc67696'
down_revision = 'cccca093ce60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('filename', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'filename')
    # ### end Alembic commands ###
