"""session additional data

Revision ID: dc65384e2010
Revises: 1a05e04104cc
Create Date: 2022-12-29 16:47:31.794394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc65384e2010'
down_revision = '1a05e04104cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('session', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('session', sa.Column('username', sa.String(length=32), nullable=True))
    op.add_column('session', sa.Column('phone', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'phone')
    op.drop_column('session', 'username')
    op.drop_column('session', 'last_name')
    op.drop_column('session', 'first_name')
    # ### end Alembic commands ###
