"""valid

Revision ID: dd655e994056
Revises: 433a47ecf8bf
Create Date: 2022-11-14 06:16:18.487020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd655e994056'
down_revision = '433a47ecf8bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'valid')
    # ### end Alembic commands ###
