---
version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(levelname)-8s | %(name)s:%(lineno)s - %(message)s"
  file:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)s - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: file
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  root:
    level: DEBUG
    handlers: [console_handler, debug_file_handler]
  
  aiogram.event:
    level: WARNING
    
  aiohttp.access:
    level: WARNING
