---
version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(levelname)-8s | %(name)s:%(lineno)s - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout

loggers:
  root:
    level: DEBUG
    handlers: [console_handler]
  
  aiogram.event:
    level: WARNING
    
  aiohttp.access:
    level: WARNING
  
  telethon:
    level: WARNING
  
  pyrogram:
    level: WARNING
  
  aiosqlite:
    level: WARNING
  
  apscheduler:
    level: WARNING

